#include "PlugBoard.hpp"
#include "Rotor.hpp"
#include "Reflector.hpp"
#include "Machine.hpp"
#include "Enigma.hpp"



using namespace std;

int main()
{
    int i(0),j(0);
    char char_to_crypt(' ');
    char char_crypted(' ');
    string text(" ");
    string text_c("");


// configuration de la machine
   
    /* Permutation used by Enigma are defined by user */

    /* Rotor used for Enigma
    I 	   EKMFLGDQVZNTOWYHXUSPAIBRCJ ekmflgdqvzntowyhxuspaibrcj 	    1930 	    Enigma I
    II 	   AJDKSIRUXBLHWTMCQGZNPYFVOE ajdksiruxblhwtmcqgznpyfvoe 	    1930 	    Enigma I
    III    BDFHJLCPRTXVZNYEIWGAKMUSQO bdfhjlcprtxvznyeiwgakmusqo 	    1930 	    Enigma I
    IV     ESOVPZJAYQUIRHXLNFTGKDCMWB esovpzjayquirhxlnftgkdcmwb 	    Dec. 1938 	M3 Army
    V 	   VZBRGITYUPSDNHLXAWMJQOFECK vzbrgityupsdnhlxawmjqofeck 	    Dec. 1938 	M3 Army
    VI     JPGVOUMFYQBENHZRDKASXLICTW jpgvoumfyqbenhzrdkasxlictw 	    1939 	    M3 & M4 Naval (FEB 1942)
    VII    NZJHGRCXMYSWBOUFAIVLPEKQDT nzjhgrcxmyswboufaivlpekqdt 	    1939 	    M3 & M4 Naval (FEB 1942)
    VIII   FKQHTLXOCBJSPDZRAMEWNIUYGV fkqhtlxocbjspdzramewniuygv
	*/

    /* Reflector used for Enigma
    reflector B	        (AY) (BR) (CU) (DH) (EQ) (FS) (GL) (IP) (JX) (KN) (MO) (TZ) (VW)
    reflector C	        (AF) (BV) (CP) (DJ) (EI) (GO) (HY) (KR) (LZ) (MX) (NW) (TQ) (SU)
    reflector B Dünn	(AE) (BN) (CK) (DQ) (FU) (GY) (HW) (IJ) (LO) (MP) (RX) (SZ) (TV)
    reflector C Dünn	(AR) (BD) (CO) (EJ) (FN) (GT) (HK) (IV) (LM) (PW) (QZ) (SX) (UY)
    */

//initialisation de la machine
// 1 - initialisation du tableau de permutation
// 2 - initialisation du premier rotor
// 3 - initialisation du deuxieme rotor
// 4 - initialisation du troisieme rotor
// 5 - initialisation du Reflector




//--------------
// Zone de test
//--------------


//text="YKAE NZAP MSCH ZBFO CUVM RMDP YCOF HADZ IZME FXTH FLOL PZLF GGBO TGOX GRET DWTJ IQHL MXVJ WKZU ASTR"*
// settings : 
//				Reflector: 	B
//				Wheel order		: III	 VI		VIII
//				Ring positions	: 01	 08		13
//				Plug pairs : AN EZ HK IJ LR MQ OT PV SW UX
//           	Message key : UZV

text = "HELLO";

Enigma t;
Machine M;



t.init();

M=t.get_machine("Enigma I");


M.setRotor("V", 1);
M.setRotor("II", 2);
M.setRotor("I", 3);

M.initRingSetting(1, 14);
M.initRingSetting(2, 22);
M.initRingSetting(3, 6);

M.initStartPosition(1, 2);
M.initStartPosition(2, 23);
M.initStartPosition(3, 24);
/*


M.initRingSetting(1, 14);
M.initRingSetting(2, 22);
M.initRingSetting(3, 6);

M.initStartPosition(1, 2);
M.initStartPosition(2, 23);
M.initStartPosition(3, 24);
*/
text = "QBLTWLDAHHYEOEFPTWYBLENDPMKOXLDFAMUDWIJDXRJZ";
//solution = DERFU EHRER ISTTO DXDER KAMPF GEHTW EITER XDOEN ITZX

/*text = "XDFIKJSQHJBJFARNGXWZTXZSKGKKVMHOTBOUBRFVQVOVXACWQNXBGDSFFBRFPSUDVGDPCJFYJSLFPDGT\
UTWRATEOZQPAXYNUXUFDMREQEDTWZTXYABHLCORSUPLGYHHWJQNPVCQZHLAPFKIBRSYZVSEFOXOLBIKD\
HZHRQWTIXDUOOCCOMQAURWCYRQZOCSIUFZTMNZMMPNSEXIAUALMKGTFHPXLCVEZBXLOCVZFYXRDMZSPT\
EUSOJGIYUQAJVOODFUSKXFVPEZTMGPJVLIMERSTXABQYRHJYTHZRYTTFIVNUOHFAGPDCGXVTHVDXNNEA\
OCAFSERBIPPCTQXLRSGYVJVNUNDVOCSKLXAMSSLR";
*/

text = "XDFIKJSQHJBJFARNGXWZ\
TXZSKGKKVMHOTBOUBRFV\
QVOVXACWQNXBGDSFFBRF\
PSUDVGDPCJFYJSLFPDGT\
UTWRATEOZQPAXYNUXUFD\
MREQEDTWZTXYABHLCORS\
UPLGYHHWJQNPVCQZHLAP\
FKIBRSYZVSEFOXOLBIKD\
HZHRQWTIXDUOOCCOMQAU\
RWCYRQZOCSIUFZTMNZMM\
PNSEXIAUALMKGTFHPXLC\
VEZBXLOCVZFYXRDMZSPT\
EUSOJGIYUQAJVOODFUSK\
XFVPEZTMGPJVLIMERSTX\
ABQYRHJYTHZRYTTFIVNU\
OHFAGPDCGXVTHVDXNNEA\
OCAFSERBIPPCTQXLRSGY\
VJVNUNDVOCSKLXAMSSLR\
DJHBYJLGBTSDBWPJPFOK\
RYPOPJIOSNEOILLQBIAD\
IDWYNENADEJAIFJRUTHL\
MGHYHLORKZIMWZXMVRHD\
PPPBDEXVXPJLZYOCXQJT\
PAQHCWODSKXFIYJVFLXN\
OJNVHMRMXYKMNHRIAGEZ\
FGCPAXRUJFKCASMQKPNA\
GILAQQPXPDONPOGBWMUL\
UAHEKQQFAMJLFDZCWZES\
RESCYCCESWROYVGJVFAK\
VWXHKSLQOQCJKXLMMYDZ\
IQNIVBPMWCNQIRPGXIBZ\
XNNGKRDPSWJXXYSCRBKT\
XRRZGIUMPYRFXSAALSDJ\
VPMCNWXFSNOERXFTAXRI\
FSKLYIYZFLHJYMIGKXET\
ZIPZQWHEDEXTKOZVPLSO\
NMRKQMVCLLRDTBOIXCPW\
RWDWLROSMAIFGCEXZWXV\
ANFBRIRTZYDAGDPTRDEZ\
RPBQSXJYLKSSQLZQUHHW\
HCNMXQIFWXPTNIAYGAKO\
MGOZCGYHSHWIBYPBSTQB\
BWCJBCZDPBCPJZYLPZKY\
WCSQJXUSFFQUKWWOFNOH\
GLTGDIMPCBLTCCICCYCO\
ZWXYVQSFHDYAVSEDPOFR\
CRIUAPGSXLTDDAVCOODW\
EVYUXWWEIIPKZYVADRQG\
DQDTVOCRTYRBRYCOOTYH\
VJLPQXQSPRYNQKELXHKO\
PBJBJKAHRJPIRGVWPUAF\
XNGYLTZCNAAGVNWMYETB\
GDAHAXCYBZFYSSPSSYXQ\
VXZTKTESFKXKAUUDROCA\
AITTDRTTHAHPQTOJUFAH\
LIOPZFQQITMMUZQKJRTD\
DIEKVIKDPYKEJKYNBJQM\
HBXHWQPFJOYAXTPEOCVO\
LNOROYNNVWZODSEDKDSW\
WYJUURLVPAXSKXPJTLHS\
ZQROTYHMTNGPNUBDGXVE\
WTXZYXAIFXSEKCDMYEIH\
SQUHARRGWWQYEDCKYNCD\
ZNTSOMGORURXSYXCQIDC\
HGPHCDYJTPWGFHXQPEZJ\
KFCWZQIJGYDNYSIFJCRN\
XCFZSKOFUNRLXQNKVDPT\
SJYOQNSCCJIBCVRPWOYS\
CUXZEBNZMHUNKEBLOMIL\
HWGJQMQETXZHNBCNQKXK\
NONSMPWNTRQQLXESEWXY\
BWPKHFIDKNMSEJRVLMWX\
DNCHZERQHKLOJDMBLSLR\
EMJWGSQFONNQVXCYSSLP\
XSRHGYNDZILRHGSQONOR\
WFUXTMPIZWCVCWKVBHIN\
JLEKDBKQAWBEVQKFTYRX\
LQASUTXBTIFFFMXSKRXN\
QIJOEABNZAIXEQRSCYFY\
TDOLAAWZVDMPUHAKERZA\
PAEIRITGMYOOBAQWQPBQ\
MCCRIGWBHRRKFRRHPGOB\
HWCTEJXPPMQOPCKTMOWJ\
QVSJRINPCKKXIDHXHPJF\
KBTZXXBIZONLSGSJXJZR\
WSHRUALBPOFIXTTKWQZM\
WLDYRQDSNZZQSWQWHONK\
ATPJKAYLQAUNVFVNQUFT\
UTWVFVSMQCMNFMCKIIKF\
FVOKUAMJANICXTFDYBVY\
LVPUPUBKOPCZJJWEYATN\
OMPVEZWUNPSEDPKPCFTD\
OTEAXKBGVSVYOPXMPHJG\
AOGRHROSRSEOMHYCZMTG\
KCQWENTZEQHJVOVFSYHV\
HPZIRPLMITTNYCWDTLGT\
VRZHBJMKLWCJTFGRYEUS\
HODIFGXOSVGPYAFGWGQD\
OQPLGYWDHBONFVQJNBBZ\
WMUTGDMDGYSCMCERBNDN\
CWOXAJVPTOYKYQADXNDM\
QWZYSAAWKVEXSLJXNCXF\
QIKFLOANCSNXHOUIHOYS\
WLRVYXSZZODPTWXFFALN\
FXZNCYZDBYLHEKOTQDZP\
DFQVIRUWRKRPVUADJGFH\
WXQJMMNWJMGDAARSYMOD\
XIOKWUNWLCBUKNIPMHPR\
EIZAZYTFBENHNNMVQHQJ\
KVPDSBSWXSMVPXFVIHAP\
DTEKFSJTZQUHBSHTPAAM\
AEOXHUPFNGYAMZHZQWRN\
MHASYADKGADYNGFNWCKK\
QPPZHIUJIMOYEMGGQSRU\
WIUTUQQHDXQTMSSTTVQR\
FVLADVZQFHTFOEHWSWTH\
VQDZEWQXZBBSSKUJDIPW\
QBHCCMTDKPSHJPTIZCWB\
JRBGMBQPKDOJBCNGCQVZ\
ULXLORYUTTKTELBJLIDV\
ZEQCYLXQQPWGKYENAEKV\
VHHVTAICGBLRRMFIACLI\
XDTMVSUHAAFQIGRYQWNW\
BAOVHOKFBKFQIOUOKGSU\
GANUKZZQJIGAZSKTAMUQ\
QDQGPGSHYTTTADSDWDRJ\
LVWDVZNPSUKKNHBLKPEF\
ZDOTIFMPQEGCPCHDOKVY\
EPRDMYMNSOTMEBISKHZC\
GTOAFFANCZZLHPMRVGBF\
TYOBIWINNZEQDZUMDAWB\
SRGOJETVRPMXWWFLZTIK\
VYZYNVSKYPQWHGYIVOWT\
EMUTEXGAMPDBTKMRWWUV\
PQNHOKYTBJIXLQRMWBCA\
IIGZKFQJVBSDOCQDPTDN\
AYAOXJARKEYIMGWAFBHZ\
YGNQJZOTCWDQSVSBSGZX\
RTTPPWIHQYTGJJYODIYR\
NVGAFKEMPSDOCWFUTKXN\
XBUWNTAXYDFMYJSQIJHY\
HUFRENSGCOIHRTXIVUYA\
TWGJUKMKNFKPSUEKQVKZ\
DDWDOCMSRVHZXPXPBYNT\
TQRGZNAVFZZHUALIXMBM\
BKPPMAQJXMWZUZLIATKM\
YLZJUHZWAGDPNOHYFHPI\
JHAQEYKYVNTJRQCAWFAR\
PXSPPXRJUFIMFBQDNZQI\
RQWQUTFNZHXXSJDSURTV\
VWGIFSDARVUKCYIRHGJC\
XVDHTCYZJZMVNHPTNRJS\
UNAYCBOXIPQEORDZKTBW\
ISZFTQGDMSLRIIVBOMOJ\
QIXJHVGEPNCNLKIIYLTU\
TLLXKHWSHMGRZLRAMZTK\
IQZDMQDQKFIHYZMJBLQL\
CTHYOKECELIVRQSBXZPF\
XWBQOXSUVWRVAEAOUJJJ\
JGBSZHYVDQSQHCUINBAD\
UPXVQGFANCGTWCKQVDVJ\
TJVAJGGURABMPJRYOMYJ\
XMNESUPUMPQKNHIRNFYC\
GYARSDOVYNKRIFONOVSF\
IBWHFYXLOZNTRRUJLTGY\
NNYOIERXSOHSDCUUVNSC\
QDBORPGVSPPPXSWDSUZB\
RKZAZGIOAITWWBAYDBAC\
EKVCTFZCRBRXVCRZRUZZ\
UDBSHSXEOZBWAXHVUYLZ\
OAHTWDYJVIDWDXJZCRRY\
VLRJCGCVIDVHEGXFXPBI\
JHINVOWELHAOZSKSACZB\
FDWUWQFTXWZAVAHATYUS\
MALKRXGMVTWBUKXMHSRT\
MBHPZOZWAXOFBWYLHDXQ\
GZJKPSAYZGJDQPOCYZPH\
VCXRWNPJGGXVOWUHJAHG\
WWQBVCDDULIAOPQVYKXM\
UQRHCEWDAOFZCXEMQXTB\
MYKTAHOFBJSTJHQMOGBD\
GTKCJARMACYAQOZZOAJN\
PIVFLRYLWBFVVWOKYAWU\
AFDADVVXBHPGWYZOVRNN\
DJYRQVPCXORSACJZNALF\
XJNZTEUZXKSXNOXXQAVD\
XBUNZGAYHJDYLGWAVJMF\
WJOQADFFIJSOFJFOFINK\
VNEQZVCHSZLRFPMUUIBT\
MOYPHPNKTVTGDZORKHNJ\
YTDVHYPJZLAJQZLRKZEN\
OJPFMDEQGQOLOPVEDVBC\
PRONHLQVLKJZWOLWJDXT\
TSVREQBMPXJNBPAEAFLH\
KTWAGXVNIRDZVUMHXZPH\
DGWAVYCOCRRQPUOHNFDE\
ZAJLYTGRNQJVOOSXOYLS\
WLFHQGKYSNWAWCXFMFSQ\
ZNKIOCLAWYGEITTMIUUC\
URRPVRDVCYVUERYOYHRC\
RXNBCMCGCSHXVVCNHCZL\
XOAKXUPWZYNBYNQEERDN\
KYPBUBJFKPWCGTZNAYAQ\
WXFEXIVSBBLQUPIQHYBJ\
TDXZAHAJKGJQKCJWNPAJ\
SMEOBOYPESRPONQUEHXW\
DNNYWXAZMTRHKWPBBWPO\
IMOYXYRNDFRXWYCTUOUB\
JJGFSLCIGEPMXLJFSXPJ\
ZMNIOFRGJWSTBQMRJSJV\
MBNBWKFDZHRQPWRPVRQE\
JDIARGIDFHBQHBHRPOOC\
TLKDNXSFZTHPYCWUYUXD\
SEEGYNOOKSEBCRGSEXXT\
LWPVJDWEJUYUGEMKZTUR\
PJUAJHYLXJGAMCXNROOX\
PPGIWYWYKAWGOACAJKOH\
JWVHVTKEEOKOFYYDCCVW\
QNLYJTSBKCPNSQJXMAND\
PRKCKRVXVJTZSOREXSAC\
JEZNMJQCSBRBGTMQYOZO\
WZUFGXWGQQTAFRPYDJQX\
XVMTCATJAUMSAGYHVCGP\
GIZCJTVRDGHLHFMYHTGH\
OWVFLIAOIVCOAYONSRBS\
XBGWGXKYTRBQRVRNTNUE\
QIQWWLOSEPIWHTTLKPXZ\
ESOUDZEGGPLOJDJYNJWL\
WDPAATMZEAUKSSYYDZHD\
JFTZVRXMXQLZFXDMGPKB\
SRZREXVYUPTSODDIOQWF\
FGRHGXPHRXXSEZBBTPRI\
MNDXCONRIZRUPKGYFRVC\
QSVDVFVFTQXLHACCSEPR\
IBHKCXIPAPMVTCWFLJWR\
SSPXSJDPAPKEFQROHQEA\
UTYLTJZXKTUBEBVXDEFR\
CSNYQMIQIHSYWSCMTKID\
PUYFXGWEHYYZXUAYQUMX\
FFEPZPKWZYXNENEKLIOX\
UXLKUDHVMJPIEHAQVDJY\
WNBSPXVYWPLJPPGYMJNR\
TVNDEPPQOJGPLJAJXSVC\
QHAXJFNSCFTVQSFQURDV\
PXFOTIJXSLBPDWLMVXUQ\
RQEWVJEYCBMEHBBHYIKF\
LTHCAWNPRIGCWGTXSFXO\
RHREJSUNEHEKBCXPCDGH\
WYJEGAKCEIHVZKADLIGH\
ZHMIJDETHDXSBQZYMDDI\
SCHIRVRROLRCYXTBWWBB\
YQNHOFKTPIKYZYOWCOCN\
IIEKKFNEGHTTYAMXYUXI\
LZVNXHZAMKWEQGFKTCWK\
MNHEXMXNRTSICIUTQEUN\
WZPEZPXAXZSOCPFTXQNS\
BRKETUBLDZWCLKGEQLKX\
AOERBVZJJSKAHUCBBARO\
IILKOKVVQQOWXHAYIANW\
SVEZAATNRDCBFZGQRIPN\
BAQQLWIENKRRYFBZUFKB\
ZDTHGRBPYINOWJDMTPUL\
GVMBHBYZIOJYPHQGBCQR\
VWQULTRNYXQJXGFMZCZD\
HGBXGKMSDTFXDZAEFJGN\
QABTJXJKAKZNPKRZYXCH\
DDKRWGCWHEZBFGFYNLFQ\
TFSLZJVYVWCFFTVIHDNK\
KMPFLMYZTTSNOUDVYSKN\
HNKVSCKMTJKYBRDATNZR\
CBTRKGADMSQLKECXSOOD\
HAIWLGYIXNZMYORVCGZO\
XPRRRANRQULPWTHQENEZ\
FRHQRXRNDYSVTYFPUBZV\
SCYOPJOWOVCMGTJZJBYJ\
TCNYDMBQOTXQMGRLIZSG\
APTKPBEROPAOKAXBRBNX\
RICBYWKPQMNZBIKJVXVJ\
VNNZKIBNXBPPRCTQWHTN\
ZYFOCIJSYRAKRIPTDROI\
YZNJHFYBMHSXZZVRXZPK\
JEALMBZHVCBYJQEPZZJW\
QQVFJUPVQMTXRNLYZERQ\
STAPFDHHKKYJZZDVTFKK\
NLMRQVQDKTKYWBHKWYDD\
YFVZHJAIKHOUSDTXCUVK\
IBBMEVNAYLSJNYMUIZMB\
SNSSHSWNKVCPIHDKPQOM\
VTHMRVYGSHGWYEMJDFFB\
TWXLYQRFHDPTCYAVRKMO\
TEHFKMLRIKTRYGARCEEU\
XCDOIJHAGAXNRFMRIBNE\
CQQDVQPFWVZCUENDKSMV\
XHONHZWKHXCHREKPCYAK\
IWFGVZYSPJBKAEPCHVKH\
QVPAPPHZWWKUZKGKJVZF\
KHSJUPJUQFXERKPRQKWF\
QMBBYCMAQEPVKCDSFNFR\
PDMGFWGTSFSEXPIGMFJO\
JTOOUPWZVKFQAIWTNQKW\
SPWVNQDBKPIVCORMTOID\
AOSXXWYKHUAVGRNDVUFW\
STSZZXCZHGMZYBMEXTAW\
XCUHSXXCFPDLLOWHVROR\
JIHFXDFIKJSQHJBJFARN\
GXWZTXZSKGKKVMHOTBOU\
BRFVQVOVXACWQNXBGDSF\
FBRFPSUDVGDPCJFYJSLF\
PDGTUTWRATEOZQPAXYNU\
XUFDMREQEDTWZTXYABHL\
CORSUPLGYHHWJQNPVCQZ\
HLAPFKIBRSYZVSEFOXOL\
BIKDHZHRQWTIXDUOOCCO\
MQAURWCYRQZOCSIUFZTM\
NZMMPNSEXIAUALMKGTFH\
PXLCVEZBXLOCVZFYXRDM\
ZSPTEUSOJGIYUQAJVOOD\
FUSKXFVPEZTMGPJVLIME\
RSTXABQYRHJYTHZRYTTF\
IVNUOHFAGPDCGXVTHVDX\
NNEAOCAFSERBIPPCTQXL\
RSGYVJVNUNDVOCSKLXAM\
SSLRDJHBYJLGBTSDBWPJ\
PFOKRYPOPJIOSNEOILLQ\
BIADIDWYNENADEJAIFJR\
UTHLMGHYHLORKZIMWZXM\
VRHDPPPBDEXVXPJLZYOC\
XQJTPAQHCWODSKXFIYJV\
FLXNOJNVHMRMXYKMNHRI\
AGEZFGCPAXRUJFKCASMQ\
KPNAGILAQQPXPDONPOGB\
WMULUAHEKQQFAMJLFDZC\
WZESRESCYCCESWROYVGJ\
VFAKVWXHKSLQOQCJKXLM\
MYDZIQNIVBPMWCNQIRPG\
XIBZXNNGKRDPSWJXXYSC\
RBKTXRRZGIUMPYRFXSAA\
LSDJVPMCNWXFSNOERXFT\
AXRIFSKLYIYZFLHJYMIG\
KXETZIPZQWHEDEXTKOZV\
PLSONMRKQMVCLLRDTBOI\
XCPWRWDWLROSMAIFGCEX\
ZWXVANFBRIRTZYDAGDPT\
RDEZRPBQSXJYLKSSQLZQ\
UHHWHCNMXQIFWXPTNIAY\
GAKOMGOZCGYHSHWIBYPB\
STQBBWCJBCZDPBCPJZYL\
PZKYWCSQJXUSFFQUKWWO\
FNOHGLTGDIMPCBLTCCIC\
CYCOZWXYVQSFHDYAVSED\
POFRCRIUAPGSXLTDDAVC\
OODWEVYUXWWEIIPKZYVA\
DRQGDQDTVOCRTYRBRYCO\
OTYHVJLPQXQSPRYNQKEL\
XHKOPBJBJKAHRJPIRGVW\
PUAFXNGYLTZCNAAGVNWM\
YETBGDAHAXCYBZFYSSPS\
SYXQVXZTKTESFKXKAUUD\
ROCAAITTDRTTHAHPQTOJ\
UFAHLIOPZFQQITMMUZQK\
JRTDDIEKVIKDPYKEJKYN\
BJQMHBXHWQPFJOYAXTPE\
OCVOLNOROYNNVWZODSED\
KDSWWYJUURLVPAXSKXPJ\
TLHSZQROTYHMTNGPNUBD\
GXVEWTXZYXAIFXSEKCDM\
YEIHSQUHARRGWWQYEDCK\
YNCDZNTSOMGORURXSYXC\
QIDCHGPHCDYJTPWGFHXQ\
PEZJKFCWZQIJGYDNYSIF\
JCRNXCFZSKOFUNRLXQNK\
VDPTSJYOQNSCCJIBCVRP\
WOYSCUXZEBNZMHUNKEBL\
OMILHWGJQMQETXZHNBCN\
QKXKNONSMPWNTRQQLXES\
EWXYBWPKHFIDKNMSEJRV\
LMWXDNCHZERQHKLOJDMB\
LSLREMJWGSQFONNQVXCY\
SSLPXSRHGYNDZILRHGSQ\
ONORWFUXTMPIZWCVCWKV\
BHINJLEKDBKQAWBEVQKF\
TYRXLQASUTXBTIFFFMXS\
KRXNQIJOEABNZAIXEQRS\
CYFYTDOLAAWZVDMPUHAK\
ERZAPAEIRITGMYOOBAQW\
QPBQMCCRIGWBHRRKFRRH\
PGOBHWCTEJXPPMQOPCKT\
MOWJQVSJRINPCKKXIDHX\
HPJFKBTZXXBIZONLSGSJ\
XJZRWSHRUALBPOFIXTTK\
WQZMWLDYRQDSNZZQSWQW\
HONKATPJKAYLQAUNVFVN\
QUFTUTWVFVSMQCMNFMCK\
IIKFFVOKUAMJANICXTFD\
YBVYLVPUPUBKOPCZJJWE\
YATNOMPVEZWUNPSEDPKP\
CFTDOTEAXKBGVSVYOPXM\
PHJGAOGRHROSRSEOMHYC\
ZMTGKCQWENTZEQHJVOVF\
SYHVHPZIRPLMITTNYCWD\
TLGTVRZHBJMKLWCJTFGR\
YEUSHODIFGXOSVGPYAFG\
WGQDOQPLGYWDHBONFVQJ\
NBBZWMUTGDMDGYSCMCER\
BNDNCWOXAJVPTOYKYQAD\
XNDMQWZYSAAWKVEXSLJX\
NCXFQIKFLOANCSNXHOUI\
HOYSWLRVYXSZZODPTWXF\
FALNFXZNCYZDBYLHEKOT\
QDZPDFQVIRUWRKRPVUAD\
JGFHWXQJMMNWJMGDAARS\
YMODXIOKWUNWLCBUKNIP\
MHPREIZAZYTFBENHNNMV\
QHQJKVPDSBSWXSMVPXFV\
IHAPDTEKFSJTZQUHBSHT\
PAAMAEOXHUPFNGYAMZHZ\
QWRNMHASYADKGADYNGFN\
WCKKQPPZHIUJIMOYEMGG\
QSRUWIUTUQQHDXQTMSST\
TVQRFVLADVZQFHTFOEHW\
SWTHVQDZEWQXZBBSSKUJ\
DIPWQBHCCMTDKPSHJPTI\
ZCWBJRBGMBQPKDOJBCNG\
CQVZULXLORYUTTKTELBJ\
LIDVZEQCYLXQQPWGKYEN\
AEKVVHHVTAICGBLRRMFI\
ACLIXDTMVSUHAAFQIGRY\
QWNWBAOVHOKFBKFQIOUO\
KGSUGANUKZZQJIGAZSKT\
AMUQQDQGPGSHYTTTADSD\
WDRJLVWDVZNPSUKKNHBL\
KPEFZDOTIFMPQEGCPCHD\
OKVYEPRDMYMNSOTMEBIS\
KHZCGTOAFFANCZZLHPMR\
VGBFTYOBIWINNZEQDZUM\
DAWBSRGOJETVRPMXWWFL\
ZTIKVYZYNVSKYPQWHGYI\
VOWTEMUTEXGAMPDBTKMR\
WWUVPQNHOKYTBJIXLQRM\
WBCAIIGZKFQJVBSDOCQD\
PTDNAYAOXJARKEYIMGWA\
FBHZYGNQJZOTCWDQSVSB\
SGZXRTTPPWIHQYTGJJYO\
DIYRNVGAFKEMPSDOCWFU\
TKXNXBUWNTAXYDFMYJSQ\
IJHYHUFRENSGCOIHRTXI\
VUYATWGJUKMKNFKPSUEK\
QVKZDDWDOCMSRVHZXPXP\
BYNTTQRGZNAVFZZHUALI\
XMBMBKPPMAQJXMWZUZLI\
ATKMYLZJUHZWAGDPNOHY\
FHPIJHAQEYKYVNTJRQCA\
WFARPXSPPXRJUFIMFBQD\
NZQIRQWQUTFNZHXXSJDS\
URTVVWGIFSDARVUKCYIR\
HGJCXVDHTCYZJZMVNHPT\
NRJSUNAYCBOXIPQEORDZ\
KTBWISZFTQGDMSLRIIVB\
OMOJQIXJHVGEPNCNLKII\
YLTUTLLXKHWSHMGRZLRA\
MZTKIQZDMQDQKFIHYZMJ\
BLQLCTHYOKECELIVRQSB\
XZPFXWBQOXSUVWRVAEAO\
UJJJJGBSZHYVDQSQHCUI\
NBADUPXVQGFANCGTWCKQ\
VDVJTJVAJGGURABMPJRY\
OMYJXMNESUPUMPQKNHIR\
NFYCGYARSDOVYNKRIFON\
OVSFIBWHFYXLOZNTRRUJ\
LTGYNNYOIERXSOHSDCUU\
VNSCQDBORPGVSPPPXSWD\
SUZBRKZAZGIOAITWWBAY\
DBACEKVCTFZCRBRXVCRZ\
RUZZUDBSHSXEOZBWAXHV\
UYLZOAHTWDYJVIDWDXJZ\
CRRYVLRJCGCVIDVHEGXF\
XPBIJHINVOWELHAOZSKS\
ACZBFDWUWQFTXWZAVAHA\
TYUSMALKRXGMVTWBUKXM\
HSRTMBHPZOZWAXOFBWYL\
HDXQGZJKPSAYZGJDQPOC\
YZPHVCXRWNPJGGXVOWUH\
JAHGWWQBVCDDULIAOPQV\
YKXMUQRHCEWDAOFZCXEM\
QXTBMYKTAHOFBJSTJHQM\
OGBDGTKCJARMACYAQOZZ\
OAJNPIVFLRYLWBFVVWOK\
YAWUAFDADVVXBHPGWYZO\
VRNNDJYRQVPCXORSACJZ\
NALFXJNZTEUZXKSXNOXX\
QAVDXBUNZGAYHJDYLGWA\
VJMFWJOQADFFIJSOFJFO\
FINKVNEQZVCHSZLRFPMU\
UIBTMOYPHPNKTVTGDZOR\
KHNJYTDVHYPJZLAJQZLR\
KZENOJPFMDEQGQOLOPVE\
DVBCPRONHLQVLKJZWOLW\
JDXTTSVREQBMPXJNBPAE\
AFLHKTWAGXVNIRDZVUMH\
XZPHDGWAVYCOCRRQPUOH\
NFDEZAJLYTGRNQJVOOSX\
OYLSWLFHQGKYSNWAWCXF\
MFSQZNKIOCLAWYGEITTM\
IUUCURRPVRDVCYVUERYO\
YHRCRXNBCMCGCSHXVVCN\
HCZLXOAKXUPWZYNBYNQE\
ERDNKYPBUBJFKPWCGTZN\
AYAQWXFEXIVSBBLQUPIQ\
HYBJTDXZAHAJKGJQKCJW\
NPAJSMEOBOYPESRPONQU\
EHXWDNNYWXAZMTRHKWPB\
BWPOIMOYXYRNDFRXWYCT\
UOUBJJGFSLCIGEPMXLJF\
SXPJZMNIOFRGJWSTBQMR\
JSJVMBNBWKFDZHRQPWRP\
VRQEJDIARGIDFHBQHBHR\
POOCTLKDNXSFZTHPYCWU\
YUXDSEEGYNOOKSEBCRGS\
EXXTLWPVJDWEJUYUGEMK\
ZTURPJUAJHYLXJGAMCXN\
ROOXPPGIWYWYKAWGOACA\
JKOHJWVHVTKEEOKOFYYD\
CCVWQNLYJTSBKCPNSQJX\
MANDPRKCKRVXVJTZSORE\
XSACJEZNMJQCSBRBGTMQ\
YOZOWZUFGXWGQQTAFRPY\
DJQXXVMTCATJAUMSAGYH\
VCGPGIZCJTVRDGHLHFMY\
HTGHOWVFLIAOIVCOAYON\
SRBSXBGWGXKYTRBQRVRN\
TNUEQIQWWLOSEPIWHTTL\
KPXZESOUDZEGGPLOJDJY\
NJWLWDPAATMZEAUKSSYY\
DZHDJFTZVRXMXQLZFXDM\
GPKBSRZREXVYUPTSODDI\
OQWFFGRHGXPHRXXSEZBB\
TPRIMNDXCONRIZRUPKGY\
FRVCQSVDVFVFTQXLHACC\
SEPRIBHKCXIPAPMVTCWF\
LJWRSSPXSJDPAPKEFQRO\
HQEAUTYLTJZXKTUBEBVX\
DEFRCSNYQMIQIHSYWSCM\
TKIDPUYFXGWEHYYZXUAY\
QUMXFFEPZPKWZYXNENEK\
LIOXUXLKUDHVMJPIEHAQ\
VDJYWNBSPXVYWPLJPPGY\
MJNRTVNDEPPQOJGPLJAJ\
XSVCQHAXJFNSCFTVQSFQ\
URDVPXFOTIJXSLBPDWLM\
VXUQRQEWVJEYCBMEHBBH\
YIKFLTHCAWNPRIGCWGTX\
SFXORHREJSUNEHEKBCXP\
CDGHWYJEGAKCEIHVZKAD\
LIGHZHMIJDETHDXSBQZY\
MDDISCHIRVRROLRCYXTB\
WWBBYQNHOFKTPIKYZYOW\
COCNIIEKKFNEGHTTYAMX\
YUXILZVNXHZAMKWEQGFK\
TCWKMNHEXMXNRTSICIUT\
QEUNWZPEZPXAXZSOCPFT\
XQNSBRKETUBLDZWCLKGE\
QLKXAOERBVZJJSKAHUCB\
BAROIILKOKVVQQOWXHAY\
IANWSVEZAATNRDCBFZGQ\
RIPNBAQQLWIENKRRYFBZ\
UFKBZDTHGRBPYINOWJDM\
TPULGVMBHBYZIOJYPHQG\
BCQRVWQULTRNYXQJXGFM\
ZCZDHGBXGKMSDTFXDZAE\
FJGNQABTJXJKAKZNPKRZ\
YXCHDDKRWGCWHEZBFGFY\
NLFQTFSLZJVYVWCFFTVI\
HDNKKMPFLMYZTTSNOUDV\
YSKNHNKVSCKMTJKYBRDA\
TNZRCBTRKGADMSQLKECX\
SOODHAIWLGYIXNZMYORV\
CGZOXPRRRANRQULPWTHQ\
ENEZFRHQRXRNDYSVTYFP\
UBZVSCYOPJOWOVCMGTJZ\
JBYJTCNYDMBQOTXQMGRL\
IZSGAPTKPBEROPAOKAXB\
RBNXRICBYWKPQMNZBIKJ\
VXVJVNNZKIBNXBPPRCTQ\
WHTNZYFOCIJSYRAKRIPT\
DROIYZNJHFYBMHSXZZVR\
XZPKJEALMBZHVCBYJQEP\
ZZJWQQVFJUPVQMTXRNLY\
ZERQSTAPFDHHKKYJZZDV\
TFKKNLMRQVQDKTKYWBHK\
WYDDYFVZHJAIKHOUSDTX\
CUVKIBBMEVNAYLSJNYMU\
IZMBSNSSHSWNKVCPIHDK\
PQOMVTHMRVYGSHGWYEMJ\
DFFBTWXLYQRFHDPTCYAV\
RKMOTEHFKMLRIKTRYGAR\
CEEUXCDOIJHAGAXNRFMR\
IBNECQQDVQPFWVZCUEND\
KSMVXHONHZWKHXCHREKP\
CYAKIWFGVZYSPJBKAEPC\
HVKHQVPAPPHZWWKUZKGK\
JVZFKHSJUPJUQFXERKPR\
QKWFQMBBYCMAQEPVKCDS\
FNFRPDMGFWGTSFSEXPIG\
MFJOJTOOUPWZVKFQAIWT\
NQKWSPWVNQDBKPIVCORM\
TOIDAOSXXWYKHUAVGRND\
VUFWSTSZZXCZHGMZYBME\
XTAWXCUHSXXCFPDLLOWH\
VRORJIHFXDFIKJSQHJBJ\
FARNGXWZTXZSKGKKVMHO\
TBOUBRFVQVOVXACWQNXB\
GDSFFBRFPSUDVGDPCJFY\
JSLFPDGTUTWRATEOZQPA\
XYNUXUFDMREQEDTWZTXY\
ABHLCORSUPLGYHHWJQNP\
VCQZHLAPFKIBRSYZVSEF\
OXOLBIKDHZHRQWTIXDUO\
OCCOMQAURWCYRQZOCSIU\
FZTMNZMMPNSEXIAUALMK\
GTFHPXLCVEZBXLOCVZFY\
XRDMZSPTEUSOJGIYUQAJ\
VOODFUSKXFVPEZTMGPJV\
LIMERSTXABQYRHJYTHZR\
YTTFIVNUOHFAGPDCGXVT\
HVDXNNEAOCAFSERBIPPC\
TQXLRSGYVJVNUNDVOCSK\
LXAMSSLRDJHBYJLGBTSD\
BWPJPFOKRYPOPJIOSNEO\
ILLQBIADIDWYNENADEJA\
IFJRUTHLMGHYHLORKZIM\
WZXMVRHDPPPBDEXVXPJL\
ZYOCXQJTPAQHCWODSKXF\
IYJVFLXNOJNVHMRMXYKM\
NHRIAGEZFGCPAXRUJFKC\
ASMQKPNAGILAQQPXPDON\
POGBWMULUAHEKQQFAMJL\
FDZCWZESRESCYCCESWRO\
YVGJVFAKVWXHKSLQOQCJ\
KXLMMYDZIQNIVBPMWCNQ\
IRPGXIBZXNNGKRDPSWJX\
XYSCRBKTXRRZGIUMPYRF\
XSAALSDJVPMCNWXFSNOE\
RXFTAXRIFSKLYIYZFLHJ\
YMIGKXETZIPZQWHEDEXT\
KOZVPLSONMRKQMVCLLRD\
TBOIXCPWRWDWLROSMAIF\
GCEXZWXVANFBRIRTZYDA\
GDPTRDEZRPBQSXJYLKSS\
QLZQUHHWHCNMXQIFWXPT\
NIAYGAKOMGOZCGYHSHWI\
BYPBSTQBBWCJBCZDPBCP\
JZYLPZKYWCSQJXUSFFQU\
KWWOFNOHGLTGDIMPCBLT\
CCICCYCOZWXYVQSFHDYA\
VSEDPOFRCRIUAPGSXLTD\
DAVCOODWEVYUXWWEIIPK\
ZYVADRQGDQDTVOCRTYRB\
RYCOOTYHVJLPQXQSPRYN\
QKELXHKOPBJBJKAHRJPI\
RGVWPUAFXNGYLTZCNAAG\
VNWMYETBGDAHAXCYBZFY\
SSPSSYXQVXZTKTESFKXK\
AUUDROCAAITTDRTTHAHP\
QTOJUFAHLIOPZFQQITMM\
UZQKJRTDDIEKVIKDPYKE\
JKYNBJQMHBXHWQPFJOYA\
XTPEOCVOLNOROYNNVWZO\
DSEDKDSWWYJUURLVPAXS\
KXPJTLHSZQROTYHMTNGP\
NUBDGXVEWTXZYXAIFXSE\
KCDMYEIHSQUHARRGWWQY\
EDCKYNCDZNTSOMGORURX\
SYXCQIDCHGPHCDYJTPWG\
FHXQPEZJKFCWZQIJGYDN\
YSIFJCRNXCFZSKOFUNRL\
XQNKVDPTSJYOQNSCCJIB\
CVRPWOYSCUXZEBNZMHUN\
KEBLOMILHWGJQMQETXZH\
NBCNQKXKNONSMPWNTRQQ\
LXESEWXYBWPKHFIDKNMS\
EJRVLMWXDNCHZERQHKLO\
JDMBLSLREMJWGSQFONNQ\
VXCYSSLPXSRHGYNDZILR\
HGSQONORWFUXTMPIZWCV\
CWKVBHINJLEKDBKQAWBE\
VQKFTYRXLQASUTXBTIFF\
FMXSKRXNQIJOEABNZAIX\
EQRSCYFYTDOLAAWZVDMP\
UHAKERZAPAEIRITGMYOO\
BAQWQPBQMCCRIGWBHRRK\
FRRHPGOBHWCTEJXPPMQO\
PCKTMOWJQVSJRINPCKKX\
IDHXHPJFKBTZXXBIZONL\
SGSJXJZRWSHRUALBPOFI\
XTTKWQZMWLDYRQDSNZZQ\
SWQWHONKATPJKAYLQAUN\
VFVNQUFTUTWVFVSMQCMN\
FMCKIIKFFVOKUAMJANIC\
XTFDYBVYLVPUPUBKOPCZ\
JJWEYATNOMPVEZWUNPSE\
DPKPCFTDOTEAXKBGVSVY\
OPXMPHJGAOGRHROSRSEO\
MHYCZMTGKCQWENTZEQHJ\
VOVFSYHVHPZIRPLMITTN\
YCWDTLGTVRZHBJMKLWCJ\
TFGRYEUSHODIFGXOSVGP\
YAFGWGQDOQPLGYWDHBON\
FVQJNBBZWMUTGDMDGYSC\
MCERBNDNCWOXAJVPTOYK\
YQADXNDMQWZYSAAWKVEX\
SLJXNCXFQIKFLOANCSNX\
HOUIHOYSWLRVYXSZZODP\
TWXFFALNFXZNCYZDBYLH\
EKOTQDZPDFQVIRUWRKRP\
VUADJGFHWXQJMMNWJMGD\
AARSYMODXIOKWUNWLCBU\
KNIPMHPREIZAZYTFBENH\
NNMVQHQJKVPDSBSWXSMV\
PXFVIHAPDTEKFSJTZQUH\
BSHTPAAMAEOXHUPFNGYA\
MZHZQWRNMHASYADKGADY\
NGFNWCKKQPPZHIUJIMOY\
EMGGQSRUWIUTUQQHDXQT\
MSSTTVQRFVLADVZQFHTF\
OEHWSWTHVQDZEWQXZBBS\
SKUJDIPWQBHCCMTDKPSH\
JPTIZCWBJRBGMBQPKDOJ\
BCNGCQVZULXLORYUTTKT\
ELBJLIDVZEQCYLXQQPWG\
KYENAEKVVHHVTAICGBLR\
RMFIACLIXDTMVSUHAAFQ\
IGRYQWNWBAOVHOKFBKFQ\
IOUOKGSUGANUKZZQJIGA\
ZSKTAMUQQDQGPGSHYTTT\
ADSDWDRJLVWDVZNPSUKK\
NHBLKPEFZDOTIFMPQEGC\
PCHDOKVYEPRDMYMNSOTM\
EBISKHZCGTOAFFANCZZL\
HPMRVGBFTYOBIWINNZEQ\
DZUMDAWBSRGOJETVRPMX\
WWFLZTIKVYZYNVSKYPQW\
HGYIVOWTEMUTEXGAMPDB\
TKMRWWUVPQNHOKYTBJIX\
LQRMWBCAIIGZKFQJVBSD\
OCQDPTDNAYAOXJARKEYI\
MGWAFBHZYGNQJZOTCWDQ\
SVSBSGZXRTTPPWIHQYTG\
JJYODIYRNVGAFKEMPSDO\
CWFUTKXNXBUWNTAXYDFM\
YJSQIJHYHUFRENSGCOIH\
RTXIVUYATWGJUKMKNFKP\
SUEKQVKZDDWDOCMSRVHZ\
XPXPBYNTTQRGZNAVFZZH\
UALIXMBMBKPPMAQJXMWZ\
UZLIATKMYLZJUHZWAGDP\
NOHYFHPIJHAQEYKYVNTJ\
RQCAWFARPXSPPXRJUFIM\
FBQDNZQIRQWQUTFNZHXX\
SJDSURTVVWGIFSDARVUK\
CYIRHGJCXVDHTCYZJZMV\
NHPTNRJSUNAYCBOXIPQE\
ORDZKTBWISZFTQGDMSLR\
IIVBOMOJQIXJHVGEPNCN\
LKIIYLTUTLLXKHWSHMGR\
ZLRAMZTKIQZDMQDQKFIH\
YZMJBLQLCTHYOKECELIV\
RQSBXZPFXWBQOXSUVWRV\
AEAOUJJJJGBSZHYVDQSQ\
HCUINBADUPXVQGFANCGT\
WCKQVDVJTJVAJGGURABM\
PJRYOMYJXMNESUPUMPQK\
NHIRNFYCGYARSDOVYNKR\
IFONOVSFIBWHFYXLOZNT\
RRUJLTGYNNYOIERXSOHS\
DCUUVNSCQDBORPGVSPPP\
XSWDSUZBRKZAZGIOAITW\
WBAYDBACEKVCTFZCRBRX\
VCRZRUZZUDBSHSXEOZBW\
AXHVUYLZOAHTWDYJVIDW\
DXJZCRRYVLRJCGCVIDVH\
EGXFXPBIJHINVOWELHAO\
ZSKSACZBFDWUWQFTXWZA\
VAHATYUSMALKRXGMVTWB\
UKXMHSRTMBHPZOZWAXOF\
BWYLHDXQGZJKPSAYZGJD\
QPOCYZPHVCXRWNPJGGXV\
OWUHJAHGWWQBVCDDULIA\
OPQVYKXMUQRHCEWDAOFZ\
CXEMQXTBMYKTAHOFBJST\
JHQMOGBDGTKCJARMACYA\
QOZZOAJNPIVFLRYLWBFV\
VWOKYAWUAFDADVVXBHPG\
WYZOVRNNDJYRQVPCXORS\
ACJZNALFXJNZTEUZXKSX\
NOXXQAVDXBUNZGAYHJDY\
LGWAVJMFWJOQADFFIJSO\
FJFOFINKVNEQZVCHSZLR\
FPMUUIBTMOYPHPNKTVTG\
DZORKHNJYTDVHYPJZLAJ\
QZLRKZENOJPFMDEQGQOL\
OPVEDVBCPRONHLQVLKJZ\
WOLWJDXTTSVREQBMPXJN\
BPAEAFLHKTWAGXVNIRDZ\
VUMHXZPHDGWAVYCOCRRQ\
PUOHNFDEZAJLYTGRNQJV\
OOSXOYLSWLFHQGKYSNWA\
WCXFMFSQZNKIOCLAWYGE\
ITTMIUUCURRPVRDVCYVU\
ERYOYHRCRXNBCMCGCSHX\
VVCNHCZLXOAKXUPWZYNB\
YNQEERDNKYPBUBJFKPWC\
GTZNAYAQWXFEXIVSBBLQ\
UPIQHYBJTDXZAHAJKGJQ\
KCJWNPAJSMEOBOYPESRP\
ONQUEHXWDNNYWXAZMTRH\
KWPBBWPOIMOYXYRNDFRX\
WYCTUOUBJJGFSLCIGEPM\
XLJFSXPJZMNIOFRGJWST\
BQMRJSJVMBNBWKFDZHRQ\
";



int textSize(text.size());
j=1;
for (int i(0); i<textSize; i++)
{
	if (text[i] == ' ')
	{
		text_c = text_c + ' ';
		continue;
	}

	char_crypted=M.activate(text[i]);
	text_c = text_c + char_crypted;
	if (j%9 == 0) { text_c = text_c + " "; }
	j++;

}



cout << "RESULTAT ---> " << text_c << endl;

 


    return 0;
}
